### ISSUE TITLE
Creating a .geno file

### ISSUE THREAD

**Issue by StuntsPT** [ekfchan/evachan.org-Rscripts#1]
This is not really a bug, but more of feature request.
I'm not sure how to obtain a _geno_ object from the documentation. Sure, I can create a random dataset, like the one you have, but what does it mean? Is it meant for haploid or diploid data? From the looks of it I'd guess haploid. Is it possible to use with diploid data?
The one thing missing here to make the script suite really awesome is a function that can convert a popular file format (I'd wager VCF as the best bet) to a _geno_ object.
Would you please consider this?
Thank you in advance.

**Comment by ekfchan** [comment]
Hi Franciso,

The geno object was originally written for diploid data.  All R functions I've written should be applicable to diploid data.  In some cases, it should also be applicable to multi-allelic data.

When these functions were originally written, they were geared towards genotyping array data.  I'm pretty sure there are more than a few tools out there that will easily convert VCF into genotype data.  But I will consider your suggestion and look into it :)

Thanks,
Eva.

---

Eva Chan | Bioinformatics Scientist
Human Comparative and Prostate Cancer Genomics Laboratory
Genomics and Epigenetics Division
Garvan Institute of Medical Research
The Kinghorn Cancer Centre
370 Victoria Street, Darlinghurst, NSW 2010, Australia
T: +61 2 9355 5853 | E: e.chan@garvan.org.au

**Comment by StuntsPT** [comment]
Thank you Eva.
In the meantime I have added the information you provide here to the README.md.
Giving back to the community, and all that. =-)
I hope it helps improve the repository.

**Comment by StuntsPT** [comment]
=-)
