### ISSUE TITLE
Providing a ref allele vector leads error when SNP is homozygous for alt state

### ISSUE THREAD

**Issue by Jesyka15** [ekfchan/evachan.org-Rscripts#3]
In the geno_to_allelecnt.R script there is an issue represented by this error:

Error in if (any(ref != markers$A1 & ref != markers$A2)) { : 
  missing value where TRUE/FALSE needed

It pops up when I provide a reference character vector. After probing, I have identified that it is generating NA's when the SNP is homozygous for the alternate state. In this case the ref is never equal to either marker A1 or A2 so then any() is never TRUE. The code stops running instead of coercing them to NA's.  In any case, I do believe the more correct thing to do here it to code SNPs homozygous for the alternate allele as '2'.

**Comment by ekfchan** [comment]
@Jesyka15 , Thanks for raising the issue.  I've made a modification to catch missing or non-existent REF alleles. The function counts the number of REF alleles, so if a REF is non-existent it will now report zero count, and if a REF is missing, the alphabetically smallest observed allele will be taken as the REF. 

Please also note that the output option has expanded to allow reporting of REF information used in the counting. 

Please let me know if this change addresses your issue.
